apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradewise-mysql
  labels:
    app: tradewise-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradewise-mysql
  template:
    metadata:
      labels:
        app: tradewise-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Vaidehi@123"
            - name: MYSQL_DATABASE
              value: "tradewisenewversion"
